import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Sobre mim
  aboutSidebar: [
    'intro',
    // Novos arquivos virão futuramente nesta pasta
  ],

  // Mini-Cursos: tutoriais e cursos
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Power BI',
      items: [
        {type: 'autogenerated', dirName: '02-power-bi'},
      ],
    },
    {
      type: 'category',
      label: 'Workshop Claude Code',
      items: [
        {type: 'autogenerated', dirName: '03-workshop-claude-code'},
      ],
    },
    {
      type: 'category',
      label: 'IA na Prática',
      items: [
        {type: 'autogenerated', dirName: '05-ia-na-pratica'},
      ],
    },
  ],
};

export default sidebars;
